When determining the id of the repository name both the name of the repository and the id of the ownser is needed because multiple users can have repositories with the same name.

diff --git a/bin/githaven-idfromreponame b/bin/githaven-idfromreponame
--- a/bin/githaven-idfromreponame
+++ b/bin/githaven-idfromreponame
@@ -1,12 +1,18 @@
 #!/bin/sh -e
-name=$1
+name="${1}"
 if [ -z "${name}" ] ; then
     echo "Error: name not specified" >&2
     exit 1
 fi
+user_id="${2}"
+if [ -z "${user_id}" ] ; then
+    echo "Error: user_id not specified" >&2
+    exit 1
+fi
+
 table="repositories"
 dbfile=`githaven-db`
-id=`sqlite3 "${dbfile}" "select id,name from ${table}" | grep "${name}$" | sed -e s/\|"${name}$"//g`
+id=`sqlite3 "${dbfile}" "select id,user_id,name from ${table}" | grep "${name}$" | grep "${user_id}" | sed -e s/\|"${user_id}"\|"${name}$"//g`
 if [ -z "$id" ] ; then
     echo "Unknown repository: $name" >&2
     exit 1
