Add more argument error checking

diff --git a/bin/githaven-checkpermissions b/bin/githaven-checkpermissions
--- a/bin/githaven-checkpermissions
+++ b/bin/githaven-checkpermissions
@@ -12,10 +12,14 @@ fi
 reponame="${3}"
 repo_owner=`echo $reponame | sed -e 's_\(.*\)/\(.*\).git_\1_g'`
 repo_name=`echo $reponame | sed -e 's_\(.*\)/\(.*\).git_\2_g'`
+if [[ -z "${repo_owner}" || -z "${repo_name}" ]] ; then
+  echo "Invalid repository: ${reponame}" >&2
+  exit 1
+fi
 repoowner_id=`githaven-idfromusername $repo_owner`
 repo_id=`githaven-idfromreponame $repo_name`
 
-# The owner of the repo can can always access the repo
+# The owner of the repository can can always access the repository
 if [ "${user_id}" = "${repoowner_id}" ] ; then
   exit 0
 fi
diff --git a/bin/githaven-db b/bin/githaven-db
--- a/bin/githaven-db
+++ b/bin/githaven-db
@@ -6,6 +6,7 @@ if [ -n "${RAILS_ENV}" ] ; then
     fi
 fi
 if [ ! -f "${db}" ] ; then
-    db=""
+    echo "Error: Unable to find database" >&2
+    exit 1
 fi
 echo $db
diff --git a/bin/githaven-idfromreponame b/bin/githaven-idfromreponame
--- a/bin/githaven-idfromreponame
+++ b/bin/githaven-idfromreponame
@@ -1,5 +1,9 @@
 #!/bin/sh -e
 name=$1
+if [ -z "${name}" ] ; then
+    echo "Error: name not specified" >&2
+    exit 1
+fi
 table="repositories"
 dbfile=`githaven-db`
 id=`sqlite3 "${dbfile}" "select id,name from ${table}" | grep "${name}$" | sed -e s/\|"${name}$"//g`
diff --git a/bin/githaven-idfromusername b/bin/githaven-idfromusername
--- a/bin/githaven-idfromusername
+++ b/bin/githaven-idfromusername
@@ -1,5 +1,9 @@
 #!/bin/bash -e
 name=$1
+if [ -z "$name" ] ; then
+  echo "Error: name not specified" >&2
+  exit 1
+fi
 table="users"
 dbfile=`githaven-db`
 id=`sqlite3 "${dbfile}" "select id,username from ${table}" | grep "${name}$" | sed -e s/\|"${name}$"//g`
